-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 08:43:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTOQUE` (
  `ESTOQUE_ID` INT NOT NULL,
  `PRO_ID` INT NULL,
  `ESTOQUE_QNTD` FLOAT NULL,
  PRIMARY KEY (`ESTOQUE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTOS` (
  `PRO_ID` INT NOT NULL,
  `PRO_NOME` VARCHAR(50) NULL,
  `PRO_VALOR` FLOAT NULL,
  `PRO_PAIS` VARCHAR(50) NULL,
  `ESTOQUE_ESTOQUE_ID` INT NOT NULL,
  PRIMARY KEY (`PRO_ID`),
  INDEX `fk_PRODUTOS_ESTOQUE1_idx` (`ESTOQUE_ESTOQUE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTOS_ESTOQUE1`
    FOREIGN KEY (`ESTOQUE_ESTOQUE_ID`)
    REFERENCES `mydb`.`ESTOQUE` (`ESTOQUE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITENS_PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITENS_PEDIDOS` (
  `PED_ID` INT NOT NULL,
  `PRO_ID` INT NULL,
  `ITENSPED_VLRUNIT` FLOAT NULL,
  `ITENSPED_QNTD` FLOAT NULL,
  `ITENSPED_VLRTOTAL` FLOAT NULL,
  `PRODUTOS_PRO_ID` INT NOT NULL,
  PRIMARY KEY (`PED_ID`),
  INDEX `fk_ITENS_PEDIDOS_PRODUTOS1_idx` (`PRODUTOS_PRO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ITENS_PEDIDOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_PRO_ID`)
    REFERENCES `mydb`.`PRODUTOS` (`PRO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDOS` (
  `PED_ID` INT NOT NULL,
  `CLI_ID` INT NULL,
  `PED_DATA` DATETIME NULL,
  `PED_VALOR` FLOAT NULL,
  `PED_ESTOQUE` FLOAT NULL,
  `ITENS_PEDIDOS_PED_ID` INT NOT NULL,
  PRIMARY KEY (`PED_ID`),
  INDEX `fk_PEDIDOS_ITENS_PEDIDOS1_idx` (`ITENS_PEDIDOS_PED_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDOS_ITENS_PEDIDOS1`
    FOREIGN KEY (`ITENS_PEDIDOS_PED_ID`)
    REFERENCES `mydb`.`ITENS_PEDIDOS` (`PED_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `CLI_ID` INT NOT NULL,
  `CLI_NOME` VARCHAR(50) NULL,
  `CLI_DATANASC` DATE NULL,
  `PEDIDOS_PED_ID` INT NOT NULL,
  PRIMARY KEY (`CLI_ID`),
  INDEX `fk_CLIENTES_PEDIDOS_idx` (`PEDIDOS_PED_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_PEDIDOS`
    FOREIGN KEY (`PEDIDOS_PED_ID`)
    REFERENCES `mydb`.`PEDIDOS` (`PED_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
